"""
Publishes the Risk Report as a GitHub Issue.
Falls back to just saving the file when running locally.
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path
import urllib.request


def publish():
    report_path = Path("data/risk_report.md")
    if not report_path.exists():
        raise FileNotFoundError("No risk report found. Run the analyzer first.")

    report = report_path.read_text()
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")

    if not token or not repo:
        print("No GITHUB_TOKEN / GITHUB_REPOSITORY — report saved locally only.")
        print("\n===== RISK REPORT =====\n")
        print(report)
        return

    # Create a GitHub Issue with the report
    title = f"AI Risk Radar Report — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    body = report + "\n\n---\n*Automatically generated by AI Project Risk Radar*"

    url = f"https://api.github.com/repos/{repo}/issues"
    data = json.dumps({"title": title, "body": body, "labels": ["risk-radar", "automated"]}).encode()

    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "AI-Project-Risk-Radar",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    with urllib.request.urlopen(req) as resp:
        result = json.loads(resp.read().decode())
        print(f"Risk report published as Issue #{result['number']}: {result['html_url']}")


if __name__ == "__main__":
    publish()
